### PR TITLE
Mask opacity

### PR DESCRIPTION
**Pull request by nholland20**
Changes to allow for an alpha channel when saving the mask .png files

### CODE REVIEW

**Comment by tvquizphd** [comment]
Thank you @nholland20 ! I will sit down to test and merge this PR soon. Is this PR still up to date with how Nanostring's fork handles opacity? I assume this PR works with [the other PR against the UI](https://github.com/labsyspharm/minerva-author-ui/pull/31).

**Comment by thejohnhoffer** [comment]
Thank you @nholland20 ! I will sit down to test and merge this PR soon. Is this PR still up to date with how Nanostring's fork handles opacity? I assume this PR works with [the other PR against the UI](https://github.com/labsyspharm/minerva-author-ui/pull/31).

**Comment by nholland20** [comment]
It's not quite up-to-date. I'm currently making a couple of changes. I will update it within the next week.

**Comment by nholland20** [comment]
This one is up-to-date. I made more recent changes to the author-ui and resubmitted the pull request after rebasing off of your master branch.

**Pull request merged**
